server:
  port: 9097

spring:
    application:
      name: miototech-miotoapp-work
    datasource:
        name: test
        url: jdbc:mysql://47.94.100.10:3306/miotoapp?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: mioto2018
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.miototech.miotoapp.work.domain

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 注册中心地址
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://10.2.3.61:8761/eureka/    #指定服务注册中心地址
#     registry-fetch-interval-seconds: 30           #服务提供者缓存清单刷新时间，默认为30秒
#   instance:
#     preferIpAddress: true                           #使用IP形式定义注册中心地址
#     instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#  Swagger配置
#swagger:
#  title: miototech-miotoapp-work----API
#  base-package: com.miototech.miotoapp.work.controller
#  contact:
#    name: wangwei
#    email: wangwei@wendu.com
#  enabled: true




